# Production Backend configuration for MonetizeAI Webinar

db_host: localhost
db_port: 3306
db_user: monetizeai_user_live
db_password: StrongPassword123!
db_name: monetizeai
server_port: "8081"

# HTTPS Configuration (for production)
enable_https: true
ssl_cert_file: "/etc/letsencrypt/live/sianmarketing.com/fullchain.pem"
ssl_key_file: "/etc/letsencrypt/live/sianmarketing.com/privkey.pem"

# CORS Configuration
allowed_origins:
  - "https://live.sianmarketing.com"
  - "https://sianmarketing.com" 